#

MAX_LINES = 3
LINE_COLOR = ["red", "blue", "yellow", "green"]
ELIMINATION_TIMER = 200
CARGO_SPOTS_PER_TROLLEY = 6
CARGO_SPAWN_TICK_DELAY = 100
STATION_SPAWN_TICK_DELAY = 500
MS_PER_TICK = 20

COST_PER_TRAIN = 0
COST_PER_LINE = 0
COST_PER_METER = 0

FIELD_WIDTH = 1100
FIELD_HEIGHT = 900
EDGE_MARGIN = 15

UI_WIDTH = 1600
UI_HEIGHT = 900
UI_SIDEBAR_MARGIN = 500
UI_STATION_RADIUS = 15